### ISSUE TITLE
New idea for recursive folder sharing

### ISSUE THREAD

**Issue by zuffoletto** [tetreum/amule-docker#1]
Thanks in advance for your work!
I pulled your container and runs smoothly.
However I would like to share to the community also files that are not stored in the /incoming directory.
Is it possible to implement an environment variable in which I choose other directories to share recursively? (For example using already allocated /movie or /series volumes).

**Comment by tetreum** [comment]
hmmm, maybe something like:
`-SHARED_FOLDERS=comma,separated,directories`
Example:
`-SHARED_FOLDERS=/storage/movies,/storage/series,/youtube/shows`

And we apply the `find` over them to have recursive folders?

**Comment by zuffoletto** [comment]
Exactly something like what you said! I’m a newbie on docker and I’m not so sure how to implement it, but I think that it should be a good feature for amule

**Comment by tetreum** [comment]
This is more a bash thing than a docker one xD 
I've made a PR that should allow it, but i didn't test it.
Once docker image is updated, could you test it?

Build status:
https://hub.docker.com/repository/registry-1.docker.io/tetreum/amule/builds/b9724172-20fe-4d36-9ae0-5e71f2e8ccfe

**Comment by zuffoletto** [comment]
For sure! Tonight I’m gonna try! Thanks

**Comment by tetreum** [comment]
Seems like build got updated, so, all you need to do is,
1. Add the new env var:
https://github.com/tetreum/amule-docker/blob/main/docker-compose.template.yml#L22

2. Rebuild the container. I believe the command is:
`docker-compose up -d amule`
But i'm not sure.

**Comment by zuffoletto** [comment]
It’s working! The directories I’ve chosen have been written in shareddir.dat.
The only thing i would suggest is to add a command that exclude hidden folders (probably system folders, those starting with @): it happens that also those are written in shareddir.dat

(for example the log says:
2021-02-25 17:34:17: No shareable files found in directory: /film/nameofthemoviefolder/@eaDir/)

**Comment by tetreum** [comment]
Hmmmmm, not sure if i can avoid that. 
Hidden folders are usually those which start with "." not with "@", unless i'm wrong and folders starting with @ are always hidden too :o
But doesn't seem to be the case, as i only find examples that ignore dot starting ones:
https://askubuntu.com/questions/266179/how-to-exclude-ignore-hidden-files-and-directories-in-a-wildcard-embedded-find

**Comment by zuffoletto** [comment]
I read that these directories are made by Synology DSM. At least the mod is working: I'll try to handle the @eaDir in other ways. Thank you for your time!
