### ISSUE TITLE
Shared folders issue

### ISSUE THREAD

**Issue by zoraksss** [tetreum/amule-docker#3]
Hi, think I found an issue.
I was trying to setup to folders in Video folder like this:

/Video/shared/(multiple folders)
/Video/not shared/(multiple folders)

In amule i configured:

Incoming /video/incoming
Temp /video/temp

And as environment SHARED_FOLDERS= /video/shared

But when amule is started in docker it list all folders, not just shared,also not shared.

Maybe i should delete amule docker and start fresh?

**Comment by tetreum** [comment]
that's pretty weird but i don't think it has to do with the container as i don't see how could it go outside the given folder :s. 
You could try rebuilding the container:
1. `docker-compose up -d --no-deps --build amule` (or the name that you set)
2. Once is started, check which folders has listed the script by looking at:
`cat /home/amule/.aMule/shareddir.dat` inside the container.

I believe you can enter the container using `docker exec -it amule /bin/bash`

**Comment by zoraksss** [comment]
Hi, 
Already found the issue, as you said, my fault
For your recursive scanning to work I also have to set the folder to scan as volume so amule can see it.
I mounted /video instead of /video/SHARED as folder and this way scanned everything in the folder...

Seems is working ok now. 

Thanks a lot for your time!
